MoSQITo:
  loudness_zwtv:
    channel:
    - Left
    - Right
    func_args:
      field_type: diffuse
    label: N
    main: 5
    parallel: true
    run: false
    statistics:
    - avg
    - 5
    - 50
  roughness_dw:
    channel:
    - Left
    - Right
    func_args: {}
    label: R
    main: avg
    parallel: true
    run: true
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - min
    - max
    - kurt
    - skew
    - avg
  sharpness_din_from_loudness:
    channel:
    - Left
    - Right
    func_args:
      field_type: free
      weighting: din
    label: S_L
    main: avg
    parallel: true
    run: true
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - min
    - max
    - kurt
    - skew
    - avg
  sharpness_din_perseg:
    channel:
    - Left
    - Right
    func_args:
      field_type: free
      nperseg: 4096
      weighting: din
    label: S_perseg
    main: avg
    parallel: false
    run: true
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - min
    - max
    - kurt
    - skew
    - avg
  sharpness_din_tv:
    channel:
    - Left
    - Right
    func_args:
      field_type: free
      skip: 0.5
      weighting: din
    label: S_din_tv
    main: avg
    parallel: true
    run: false
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - min
    - max
    - kurt
    - skew
    - avg
PythonAcoustics:
  LAeq:
    channel:
    - Left
    - Right
    func_args:
      method: average
      time: 0.125
    label: LAeq
    main: avg
    parallel: false
    run: true
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - avg
    - min
    - max
    - kurt
    - skew
  LCeq:
    channel:
    - Left
    - Right
    func_args:
      method: average
      time: 0.125
    label: LCeq
    main: avg
    parallel: false
    run: true
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - min
    - max
    - kurt
    - skew
    - avg
  LZeq:
    channel:
    - Left
    - Right
    func_args:
      method: average
      time: 0.125
    label: LZeq
    main: avg
    parallel: false
    run: true
    statistics:
    - 5
    - 10
    - 50
    - 90
    - 95
    - min
    - max
    - kurt
    - skew
    - avg
  SEL:
    channel:
    - Left
    - Right
    func_args: {}
    label: SEL
    main: null
    parallel: false
    run: true
    statistics: null
scikit-maad:
  all_spectral_alpha_indices:
    channel:
    - Left
    - Right
    func_args: {}
    label: label
    main: null
    parallel: false
    run: true
    statistics: null
  all_temporal_alpha_indices:
    channel:
    - Left
    - Right
    func_args: {}
    label: label
    main: null
    parallel: false
    run: true
    statistics: null
version: '1.0'
